### ISSUE TITLE
Installing with pathogen

### ISSUE THREAD

**Issue by juanpastas** [matze/vim-move#11]
Hi,

I did:

```
git clone https://github.com/matze/vim-move.git ~/.vim/bundle/vim-move
```

I have other plugins working on `~/.vim/bundle`.

But I can't move lines with `alt+j` or `alt+k`. How could I troubleshoot?

**Comment by matze** [comment]
You can see if the keys are mapped using the `:map` command. I think the real problem lies in your terminal emulator. For gnome-terminal I need [specific](https://github.com/matze/configs/blob/6350c80f7aac77a2c0b3400c205b9cb8d660bbd8/.vimrc#L133-L136) maps (GitHub doesn't show the ^[ characters) to make the Alt keys work.

**Comment by juanpastas** [comment]
It works on GVim, I will use that for now. Thanks.
