### ISSUE TITLE
Noremap version of mappings

### ISSUE THREAD

**Issue by aharris88** [matze/vim-move#12]
When I use the normal `nmap` or `vmap`, the plugin works fine, but if I try to use `nnoremap` or `vnoremap`, it doesn't work at all. Why is this? I think it's better to always use the noremap versions. Can the plugin be updated to support this?

**Comment by matze** [comment]
> I try to use nnoremap or vnoremap, it doesn't work at all. Why is this?

It is because I provide `<Plug>` key sequences which is the preferred way to provide mappable actions to the user. Longer story: we provide default mappings based on a custom key modifier. In order not to clash with the user's already defined maps they are mapped using the non-recursive mapping which may then be remapped (implicitly) by the user. For this to work the rhs (i.e. `<Plug>` sequence) must be remappable. This is actually pretty common if you have a look at other popular Vim plugins.

By the way, although it is definitely recommended to map keys via `*noremap` in this case it is no problem because the `<Plug>` key sequences are themselves mapped via `*noremap` thus no danger of infinite recursion.
