### ISSUE TITLE
add option to not map line up/down

### ISSUE THREAD

**Issue by jwkvam** [matze/vim-move#22]
I really like having these [mappings](https://github.com/w0rp/ale#5vii-how-can-i-navigate-between-errors-quickly) that map `<c-j>` and `<c-k>` for ale in normal mode to navigate errors. For now I've deleted those [mappings](https://github.com/matze/vim-move/blob/master/plugin/move.vim#L159-L160) from this plugin. I thought it would be nice to have those mappings be configurable to be disabled. As it's not too much effort to visually select the current line.

**Comment by cookiengineer** [comment]
I don't think this plugin is maintained anymore. @matze somewhat reacted to a pull request and its review, but does not to issues, I guess? :confused:

Just stumbled upon your issue while refactoring my vimrc, and I would confirm that indeed something like this would be nice as a feature and I planned on implementing it myself via exposing the `Move` methods globally so that they can be rebound by the user to their liking.

Not sure what you think of that, @jwkvam - Maybe it makes sense to fork vim-move in case its not fitting here?

**Comment by matze** [comment]
I still do maintain the plugin for whatever there is to maintain. But it works for my daily usage thus any further feature requests should come with a working pull request as well.

**Comment by jwkvam** [comment]
At the time I just modified it locally. For unrelated reasons, I don't use this plugin anymore (I was running out of keybinds). 

Maybe the custom modifier could be used? Sorry I'm a little out of the game here, not too invested right now.

https://github.com/matze/vim-move/blob/master/README.md#customization

**Comment by yous** [comment]
There is `g:move_map_keys` to disable mappings. This will work:

``` vim
" Disable whole mappings
let g:move_map_keys = 0

vmap <C-j> <Plug>MoveBlockDown
vmap <C-k> <Plug>MoveBlockUp
vmap <C-h> <Plug>MoveBlockLeft
vmap <C-l> <Plug>MoveBlockRight

nmap <C-h> <Plug>MoveCharLeft
nmap <C-l> <Plug>MoveCharRight
```

**Comment by matze** [comment]
I think @yous solution concludes that issue.
